name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
        issues: write
        pull-requests: write
        contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - uses: cirruslabs/swiftlint-action@v1
      with:
        version: latest
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
